### ISSUE TITLE
How to generate TileConfiguration.txt.

### ISSUE THREAD

**Issue by kuldeep203** [InsightSoftwareConsortium/ITKMontage#212] opened 2022-12-28 09:33 UTC
I am working on digital microscopy for whole slide imaging. i am capturing lots of images and at last i need to stitch all of them to create a single image. i was trying your python example but dont know how to create TileConfiguration.txt. Can you help me in that case.

**Comment by dzenanz** [comment] 2022-12-28 16:30
This is somewhat a duplicate of #208. If you don't want to create TileConfiguration.txt by hand, you could use  [Image Stitching Plugin](https://imagej.net/plugins/image-stitching) for Fiji to create it.

**Comment by zhusihan-python** [comment] 2022-12-29 09:02
the origin is at the top-left corner, suppose the motor moves like this
```
↓  ↑→ ↓
↓  ↑  ↓
↓→ ↑  ↓
```
got pictures like below
```
000_000.jpg  001_002.jpg  002_000.jpg
000_001.jpg  001_001.jpg  002_001.jpg
000_002.jpg  001_000.jpg  002_002.jpg
```

(1-overlap_ratio)*height=h_offset is vertical expect offset
(1-overlap_ratio)*width=w_offset is horizontal expect offset

the TileConfiguration.txt should be like this
```
dim = 2
000_000.jpg;;(0, 0)
001_002.jpg;;(1*w_offset , 0)
002_000.jpg;;(2*w_offset , 0)
000_001.jpg;;(0, 1*h_offset )
001_001.jpg;;(1*w_offset, 1*h_offset )
002_001.jpg;;(2*w_offset, 1*h_offset )
000_002.jpg;;(0, 2*h_offset )
001_000.jpg;;(1*w_offset, 2*h_offset )
002_002.jpg;;(2*w_offset, 2*h_offset )
```

**Comment by ckolluru** [comment] 2023-05-29 18:31
For 2D stitching, if you have the starting XY positions for the tiles, I think the following code should arrange them as needed for TileConfiguration.txt

```
x_positions = xy_positions[:,0]
y_positions = xy_positions[:,1]

sorted_indices = np.lexsort((x_positions, y_positions))
xy_positions_sorted = xy_positions.take(tuple(sorted_indices), axis=0)
```

**Comment by dzenanz** [comment] 2024-04-25 21:17
Reopen the issue if there are further details.

**Closed by dzenanz** 2024-04-25 21:17 UTC
